fix(transport): do not callback after listen errored
libp2p/js-libp2p-swarm pull request #139
Opened 2016-12-14 19:50 UTC by dignifiedquire

Fixes the error seen in https://github.com/haadcode/orbit/issues/210#issuecomment-267102858

2016-12-14 19:56 UTC, daviddias requested changes

2016-12-14 19:56 UTC, diasdavid commented on src/transport.js
> +
Good catch!

Can we make it more simpler with

```
listener.once('error', cb)
...
listener.removeListener('error', cb)
```

2016-12-14 20:06 UTC, dignifiedquire commented on src/transport.js
> +
We can't, that's what it was before, which doesn't catch the case where an error happens but the listen callback still happens

2016-12-15 01:15 UTC, michaelfakhri commented on src/transport.js
> +
May I offer an alternative to these two ways?
```
listener.once('error', (err) => {
  if (err !== 'timeout') { // timeout handled internally in libp2p-webrtc-star when connect_error is fired up
    listener.close() // data packet parse error
  }
})
```
Reasoning: socket io client emits two events on connection error (connect_error and error). callback is attached internally to connect error. so no need to attach again for error. BUT error is also called on a data packet parse error, so we need some kind of error handling for the two scenarios. Hence ^

2016-12-15 07:50 UTC, dignifiedquire commented
@michaelfakhri thanks but as far as I know this handler at the moment doesn't use socket.io. Only pull-ws, net and webrtc

2016-12-15 18:47 UTC, michaelfakhri commented
@dignifiedquire the webrtc transport uses socket.io internally to connect to the signalling server. Isn't that where you are seeing the error, while connecting to the sig server? 
Actually another alternative is to remove the connect_error event handler from the webrtc transport, that way its much cleaner and simpler. since I doubt parse errors are actually the problem here. Are they?

2016-12-15 18:53 UTC, michaelfakhri commented
A bit of background: I am seeing the same exact error "callback was already called" while testing the browser application I am building using libp2p. The reason in my case being the restarting of the sig server while changing between mocha -> karma tests. I believe your error would be something similar  relating to the sig server connection.

2016-12-16 12:47 UTC, dignifiedquire commented
@michaelfakhri I think I was seeing the issue in other cases as well. But in any case the handling here should not include checking for transport specific errors, if signaling server transport emits errors that shouldn't be handled as such in here, they should not be emitted from there in the first place. 

I've added another important fix for close behaviour. Before we were not waiting for the stream muxer to properly close. Now we do. This depends on https://github.com/libp2p/js-libp2p-spdy/pull/47

2016-12-16 22:57 UTC, michaelfakhri commented
@dignifiedquire Yes I completely agree with everything you said.

Just for reference: here is the error I was talking about earlier, it isn't actually caused by the reason I mentioned earlier. I wrote a test that emits the callback was already called error. I think its caused by multiple events firing internally inside socket.io-client. I haven't looked that deep into it but I can tell something quite weird is going on and I dont think its any of the code in here that's directly causing this error.

https://github.com/michaelfakhri/js-libp2p-swarm/commit/0d1f8bf7bc0a9bf397ed0add21643201da40ad9d

2016-12-18 07:20 UTC, daviddias approved these changes
Small question, otherwise LGTM

2016-12-18 07:20 UTC, diasdavid commented on src/index.js
> +      }, callback)
Why can't all they be closed in parallel?

2016-12-18 07:55 UTC, dignifiedquire commented on src/index.js
> +      }, callback)
`each` is parallel

2016-12-18 07:57 UTC, diasdavid commented on src/index.js
> +      }, callback)
Interesting, thank you :)

2016-12-18 07:58 UTC, daviddias approved these changes
Let's ensure CI is happy before merging

2016-12-18 08:06 UTC, dignifiedquire commented
Yeah looks like one test is unhappy, fixing now.

2016-12-18 08:16 UTC, dignifiedquire commented
should be happy now

2016-12-18 09:50 UTC, diasdavid commented
@dignifiedquire CI still says `no`

2016-12-18 09:51 UTC, dignifiedquire commented
@diasdavid I don't get it :/ all passing locally

2016-12-18 09:59 UTC, diasdavid commented
@dignifiedquire the only different to CI, is that CI is doing a fresh npm install every time, have you tried that in your local machine?

2016-12-18 10:00 UTC, dignifiedquire commented
Yeah I did, could you try as well?

2016-12-18 10:25 UTC, diasdavid commented
So, the error is:

```
  1) libp2p-swarm high level API - with everything mixed all together! close a muxer emits event:
     Uncaught AssertionError: expected true to not exist
      at conn.getPeerInfo (test/09-swarm-with-muxing.node.js:214:27)
```

But that line is on the `dial from tcp+ws to tcp+ws`, meaning that conn.getPeerInfo is being resolved after the hangup (CI is slower on things).

2016-12-18 10:49 UTC, dignifiedquire commented
@diasdavid ready for squash and ship

2016-12-18 11:20 UTC, merged

2016-12-18 11:22 UTC, diasdavid commented
squashed and shipped :)