test: add sample network circuit relay tests
libp2p/js-libp2p-swarm pull request #275
Opened 2018-08-14 16:19 UTC by jacobheun

Added some additional tests around circuit relays to make sure that various dials are working properly and that peer connection events are being sent for peers connecting via the relay (https://github.com/libp2p/js-libp2p-circuit/issues/26)

2018-08-14 17:42 UTC, dryajov requested changes
should use ephemeral ips and ports, other than that 👍

2018-08-14 17:42 UTC, dryajov commented on test/circuit-relay.node.js
> +      bootstrapPeer.multiaddrs.add('/ip4/127.0.0.1/tcp/9100')
should use ephemeral ips and ports

2018-08-15 12:36 UTC, jacobheun commented
Ports are now being discovered. I noticed I was also not stopping the swarms after the tests, so that is being done now. Most of the tests in switch are not using ephemeral ports. If we're doing actual connection testing we should migrate those over.

2018-08-15 16:13 UTC, dryajov commented
> Most of the tests in switch are not using ephemeral ports.

huh, true - I forgot about #227! But you're not using port `0` either way so I think this will work?

2018-08-15 16:14 UTC, dryajov approved these changes

2018-08-15 16:54 UTC, merged